version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests: # test criteria: the id is unique and not null
                - unique
                - not_null
                - accepted_values:
                    values: [1, 2]
                    quote: false

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - relationships:
                    to: ref('my_first_dbt_model')
                    field: id # the id field in the my_second_dbt_model need to reference to my_first_dbt_model

    - name: snowflake_customer_purchases
      description: "the total purchases for each customer in snowflake sample data"
      columns:
        - name: c_custkey
          tests:
            - unique
            - not_null
            -
    # add incremental model
    - name: incremental_model_time
    - name: playing_with_tests
      columns:
        - name: c_custkey
          tests:
            - unique
            - not_null
        - name: c_mktsegment
          tests:
            - accepted_values:
                values: ['BUILDING', 'AUTOMOBILE', 'MACHINERY', 'HOUSEHOLD', 'FURNITURE']

#sources:
#  - name: sample
#    database: snowflake_sample_data  # Tell dbt to look for the source in the "raw" database
#    schema: tpch_sf1
#    tables:
#      - name: customer
#        columns:
#          - name: c_custkey
#            tests:
#              - unique
#              - not_null
#      - name: orders
#  - name: sample2
#    database: snowflake_sample_data
#    schema: tpch_sf001
#    tables:
#      - name: customer